## Instructions

#### 。 This homework has two parts
    1. There are 6 simple questions, just follow the instrctions and get the same output as the following.
    2. It's how simple neural networks work. As the same as part 1, just follow the instructions and get the same output

#### 。 All of this homework should use Numpy or Pandas

#### 。 Please follow the same variable name as the instuctions of every questions 

## Part 1

**1. Import both numpy and pandas packages**

In [86]:
import numpy as np
import pandas as pd

**2. Create a 3x3 matrix with values ranging from 0 to 8**

In [87]:
np.arange(9).reshape(3,3)

#np.array([i for i in range(9)]).reshape(3,3)

#array([[0, 1, 2],
#       [3, 4, 5],
#       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**3. Create a 5x5 matrix with row values ranging from 0 to 4**

In [88]:
np.array([i for i in range(5)]*5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

**4. How to swap the first and second rows of a**

In [89]:
a = np.arange(25).reshape(5,5)

#print(a)

a[[0,1], :] = a[[1,0],:]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**5. Give two ways to show how to get the n largest values of a (no sort the value is fine)**

In [90]:
# Don't need to change this cell
a = np.arange(100)
np.random.shuffle(a)
n = 5
#print(a)

In [91]:
# Way 1
# [95 96 97 98 99]

np.sort(a)[-5:]

array([95, 96, 97, 98, 99])

In [92]:
# Way 2
# [99 98 97 95 96]
-np.sort(-a)[:5]

array([99, 98, 97, 96, 95])

**6. Compare if array a and array b is totally the same**

In [93]:
np.random.seed(123)
a = np.round(np.random.random(100)*100, 0)
b = np.random.randint(1, 100, 100)

# Put your code here
print(a)
print(b)

np.array_equal(a, b)

[ 70.  29.  23.  55.  72.  42.  98.  68.  48.  39.  34.  73.  44.   6.
  40.  74.  18.  18.  53.  53.  63.  85.  72.  61.  72.  32.  36.  23.
  29.  63.   9.  43.  43.  49.  43.  31.  43.  89.  94.  50.  62.  12.
  32.  41.  87.  25.  48.  99.  52.  61.  12.  83.  60.  55.  34.  30.
  42.  68.  88.  51.  67.  59.  62.  67.  84.   8.  76.  24.  19.  57.
  10.  89.  63.  72.   2.  59.  56.  16.  15.  70.  32.  69.  55.  39.
  93.  84.  36.   4.  30.  40.  70. 100.  36.  76.  59.  69.  15.  40.
  24.  34.]
[78  9 79  7 66 95 71 41 75 77 77 26  8 14 45  2 42 79 57 88 64 98  4 18
 89 88 70 98 51  3 19 47 46 58 36 19 92 47 55 74 82 63 68 12 27 93 76 11
  4 46 59 60 24 26 28 58  4 79 86 60 49 57 88 88  5 70 57 61 10 67 34 70
 10 80 29 67 11  4 49  4 24 92 56 35 38 50 88 86 26 18 59 67 46 11  9 97
 26 68 66  8]


False

## Part 2

### Online Shoppers Purchasing Intention Dataset

The dataset consists of 10 numerical and 8 categorical attributes. The 'Revenue' attribute can be used as the class label.

* ``0 Administrative``, ``1 Administrative Duration``, ``2 Informational``, ``3 Informational Duration``, ``4 Product Related`` and ``5 Product Related Duration`` - represent the number of different types of pages visited by the visitor in that session and total time spent in each of these page categories. The values of these features are derived from the URL information of the pages visited by the user and updated in real time when a user takes an action, e.g. moving from one page to another. 


* ``6 Bounce Rate``, ``7 Exit Rate`` and ``8 Page Value`` - represent the metrics measured by "Google Analytics" for each page in the e-commerce site. The value of "Bounce Rate" feature for a web page refers to the percentage of visitors who enter the site from that page and then leave ("bounce") without triggering any other requests to the analytics server during that session. The value of "Exit Rate" feature for a specific web page is calculated as for all pageviews to the page, the percentage that were the last in the session. The "Page Value" feature represents the average value for a web page that a user visited before completing an e-commerce transaction. 


* ``9 Special Day`` - indicates the closeness of the site visiting time to a specific special day (e.g. Mother’s Day, Valentine's Day) in which the sessions are more likely to be finalized with transaction. The value of this attribute is determined by considering the dynamics of e-commerce such as the duration between the order date and delivery date. For example, for Valentina’s day, this value takes a nonzero value between February 2 and February 12, zero before and after this date unless it is close to another special day, and its maximum value of 1 on February 8. 


* The dataset also includes ``11 operating system``, ``12 browser``, ``13 region``, ``14 traffic type``, ``15 visitor type`` as returning or new visitor, a Boolean value indicating whether the date of the visit is ``16 weekend``, and ``9 month of the year``.


---
* **``17 Revenue``** - binary labels



* More information of this data: [UCI | Online Shoppers Purchasing Intention Dataset](https://archive.ics.uci.edu/ml/datasets/Online+Shoppers+Purchasing+Intention+Dataset#)

**Use pandas to import the data and check the shape of dataset and save it as `" shoppers "`**

In [122]:
shoppers = pd.read_csv('online_shoppers_intention.csv')
shoppers.head(5)

Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0   
1               0                      0.0              0   
2               0                      0.0              0   
3               0                      0.0              0   
4               0                      0.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                     0.0               1                 0.000000   
1                     0.0               2                64.000000   
2                     0.0               1                 0.000000   
3                     0.0               2                 2.666667   
4                     0.0              10               627.500000   

   BounceRates  ExitRates  PageValues  SpecialDay Month  OperatingSystems  \
0         0.20       0.20         0.0         0.0   Feb                 1   
1         0.00       0.10         0.0         0.0   Feb                 2   
2         0.20       0.20         0.0         0.0   Feb                 4   
3         0.05       0.14         0.0         0.0   Feb                 3   
4         0.02       0.05         0.0         0.0   Feb                 3   

   Browser  Region  TrafficType        VisitorType  Weekend  Revenue  
0        1       1            1  Returning_Visitor    False    False  
1        2       1            2  Returning_Visitor    False    False  
2        1       9            3  Returning_Visitor    False    False  
3        2       2            4  Returning_Visitor    False    False  
4        3       1            4  Returning_Visitor     True    False

In [117]:
np.shape(shoppers)

(12330, 18)

**Use pandas function to let label be numeric as below and save it as `" label "`**

In [123]:
label = shoppers['Revenue']
label = label.map({False:0,True:1})
np.array(label)

array([0, 0, 0, ..., 0, 0, 0])

**See some information of this data**

In [97]:
shoppers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Administrative           12330 non-null  int64  
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64  
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64  
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object 
 11  OperatingSystems         12330 non-null  int64  
 12  Browser                  12330 non-null  int64  
 13  Region                   12330 non-null  int64  
 14  TrafficType           

In [98]:
label.value_counts()

False    10422
True      1908
Name: Revenue, dtype: int64

**Choose column [1, 4, 5, 11, 12, 13] and turn into numpy array ``" x "``**

In [127]:
x = np.array(shoppers.iloc[:,[1,4,5,11,12,13]])

In [128]:
x

array([[  0.  ,   1.  ,   0.  ,   1.  ,   1.  ,   1.  ],
       [  0.  ,   2.  ,  64.  ,   2.  ,   2.  ,   1.  ],
       [  0.  ,   1.  ,   0.  ,   4.  ,   1.  ,   9.  ],
       ...,
       [  0.  ,   6.  , 184.25,   3.  ,   2.  ,   1.  ],
       [ 75.  ,  15.  , 346.  ,   2.  ,   2.  ,   3.  ],
       [  0.  ,   3.  ,  21.25,   3.  ,   2.  ,   1.  ]])

**Use numpy function to load weight data, bias data and check their shape**

In [101]:
weight_1 = np.load('layer_1_weight.npy')
weight_2 = np.load('layer_2_weight.npy')

bias_1 = np.load('layer_1_bias.npy')
bias_2 = np.load('layer_2_bias.npy')

In [104]:
print('weight_1 shape:',np.shape( weight_1))
print('weight_2 shape:',np.shape( weight_2))
print('')
print('bias_1 shape:',np.shape(bias_1) )
print('bias_2 shape:',np.shape(bias_2) )

weight_1 shape: (6, 32)
weight_2 shape: (32, 2)

bias_1 shape: (32,)
bias_2 shape: (2,)


**Use numpy function to compute `" x "` and weight_1 matrix multiplication, and check the shape**

In [129]:
x = np.dot(x,weight_1) 

In [130]:
np.shape(x)

(12330, 32)

**Use numpy function to compute `" x "` and bias_1 matrix addtion, and check the shape**

In [131]:
x = x + bias_1

In [132]:
np.shape(x)

(12330, 32)

**Use numpy function to compute `" x "` and weight_2 matrix multiplication, and check the shape**

In [133]:
x = np.dot(x,weight_2)

In [134]:
np.shape(x)

(12330, 2)

**Use numpy function to compute `" x "` and bias_2 matrix addtion, and check the shape**

In [135]:
x = x + bias_2

In [136]:
np.shape(x)

(12330, 2)

**Check if your x is same as below**

In [137]:
x

array([[ -0.42815397,  -0.58708018],
       [ 17.76804854, -12.0093477 ],
       [ -1.07327452,  -3.72237766],
       ...,
       [ 51.70654464, -34.08445513],
       [110.52965928, -73.95802223],
       [  5.45892153,  -4.42243782]])

**Use numpy function to find out each row which one value is bigger, and save it as `" pre "`**

In [138]:
def cal_bigger(arr):
    if  arr[0] > arr[1] :
        return 0
    else:
        return 1

In [139]:
pre = np.apply_along_axis(cal_bigger, axis=1, arr=x)
pre

array([0, 0, 0, ..., 0, 0, 0])

**Use numpy function to check if `pre[i]` is the same as `label[i]`, and save it as `" check "`**

In [148]:
check = np.where(pre == label,1,-1)
check

array([1, 1, 1, ..., 1, 1, 1])

**Use numpy function to calculate the accuracy**

In [149]:
print('accuracy:',np.count_nonzero(check==1)/len(check))

accuracy: 0.8284671532846716
